apiVersion: v1
kind: Pod
metadata:
  name: one-app-1
  namespace: test
  labels:
    app: one-app
    version: v1
spec:
  containers:
    - name: app-ctr-1
      image: sample-app
      ports:
        - name: web
          containerPort: 8095
          protocol: TCP
