apiVersion: v1
kind: Service
metadata:
  name: simple-app-srv
  namespace: test
spec:
  selector:
    app: one-app
    version: v1
  type: NodePort
  ports:
    - protocol: TCP
      port: 8087
      name: non-secure
      targetPort: web
      nodePort: 30445

